services:

#123
  auth:
    restart: always
    build: ./auth
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./auth/.env
    networks:
      - app-net
############################123

  ui:
    restart: always
    build: ./ui
    depends_on:
      - auth
      - weather
    env_file:
      - ./ui/.env
    ports:
      - "3000:3000"
    networks:
      - app-net
   
  weather:
    restart: always
    build: ./weather
    ports:
      - "5000:5000"
    env_file:
      - ./weather/.env
    networks:
      - app-net


  
  # nginx:
  #   image: nginx
  #   container_name: nginx-compose-container-weather
  #   ports:
  #     - "8090:80"
  #   depends_on:
  #     - ui
  #   networks:
  #     - app-net
  #   volumes:
  #     - ./nginx/default.config:/etc/nginx/conf.d/default.conf


  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: authdb
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/mysql


##################################
networks:
  app-net:
    driver: bridge
volumes:
  db-data: